### ISSUE TITLE
Compile error - GoogleAuth - buildozer

### ISSUE THREAD

**Issue by Kulothungan16** [shashi278/social-auth-kivy#12]
**Describe the bug**
When build a kivy app that uses `kivyauth` using buildozer it raises this [error](https://ghostbin.com/paste/bf4ok)
[buildozer.spec](https://ghostbin.com/paste/y9JJM)

**Comment by shashi278** [comment]
Hi! `fontVariationSettings` has been added in Android API 28 and above so could you try to re-build after changing API to 28 instead of 27 in your buildozer.spec file? Update `android.api=27` to Update `android.api=28` and let me know if that works.

**Comment by Kulothungan16** [comment]
So, what I need to use in `android.minapi`?

**Comment by shashi278** [comment]
Keep it default

**Comment by Kulothungan16** [comment]
The app builded successfully,
But when I try to login it opens google dialog box, when I click user's google account
The app gets restarted
This is error that occured `04-19 10:58:35.134 18327 18327 I python  : [INFO   ] [KivyAuth    ] Error signing in using Google. JVM exception occurred: 10:`

**Comment by Kulothungan16** [comment]
Full log: https://ghostbin.com/paste/0ildq

**Comment by shashi278** [comment]
> This is the error that occured `04-19 10:58:35.134 18327 18327 I python : [INFO ] [KivyAuth ] Error signing in using Google. JVM exception occurred: 10:`

Hard to tell where could be the error. It's not giving out any extra information. Can't say much without looking at the code :confused:

**Comment by shashi278** [comment]
Hi @Kulothungan16 It's working fine on my end. See below video and logcat image:

https://user-images.githubusercontent.com/37111736/115399473-e1b1e380-a205-11eb-9381-5ab5d4f1411d.mp4

![Screenshot from 2021-04-20 18-17-34](https://user-images.githubusercontent.com/37111736/115399497-e7a7c480-a205-11eb-8d73-7131406496ab.png)

Here's something you can try:
* Make sure you've provided the correct package name in the google console while creating OAuth client for android
* Re-check your sha fingerprint

Also, you don't client ID for android and you need both the client ID and secret for desktop.

**Comment by Kulothungan16** [comment]
You are correct I have specified `org.kivy.auth` for building the app but I provided `com.kivy.auth` while creating OAuth client. 😅
Give me some time to build and check

**Comment by Kulothungan16** [comment]
Hey @shashi278 thank you very much!, all are working fine... 🙏

**Comment by shashi278** [comment]
Really glad to know that :smile: and thanks for testing it out
