### ISSUE TITLE
Bug in the demo app

### ISSUE THREAD

**Issue by Zer0-Official** [shashi278/social-auth-kivy#16]
**Describe the bug**
Every time I open the demo app, it closes after the loading screen

**To Reproduce**
Open the app

**Expected behavior**
The app should stay open and function as meant to.

**Smartphone**
 - Device: Samsung A71
 - OS: Android 11

**Comment by shashi278** [comment]
Hi @Zer0-Official, thanks for pointing it out. Did you install the apk directly or from the playstore?

**Comment by Zer0-Official** [comment]
The playstore

**Comment by shashi278** [comment]
@Zer0-Official Yeah probably because I messed things up while experimenting with something related to the playstore. Could you try it out with the apk instead? Hopefully, that should be working. Meanwhile, I'll try to rollback to the last working version on the playstore.

**Comment by raffieeey** [comment]
I too experience this bug on the playstore app.

Smartphone

Device: Samsung Note 9
OS: Android 10

**Comment by Sprbb** [comment]
demo app still not working.

**Comment by shashi278** [comment]
The one on the playstore is a crap. I'll try to update it if time permits. The library itself should be working fine tho.

**Comment by shashi278** [comment]
Hi all! Just a heads up, the application in the playstore should be working now. :v:
