### ISSUE TITLE
What value should I use for the "Authorized redirect URIs" parameter?

### ISSUE THREAD

**Issue by YuriSilenok** [shashi278/social-auth-kivy#18]
The code of the problem I'm solving is in [this branch](https://github.com/YuriSilenok/membership-accounting/tree/issue-4).

I set up everything I could, but I couldn't figure out what to write in this field?
![image](https://user-images.githubusercontent.com/14871471/153937004-d5fbecee-e2b8-4a8c-8536-2b43278dc946.png)
I get an error: `400: redirect_uri_mismatch`

**Comment by YuriSilenok** [comment]
I want to add that I am trying to run my application on Windows Desktop and authorization takes place through the browser.

**Comment by shashi278** [comment]
@YuriSilenok  Are you still facing this?

**Comment by YuriSilenok** [comment]
@shashi278 
Yes, the question is still relevant. 
I would be grateful to you for any information about that.

**Comment by shashi278** [comment]
It should be just the url where you want it to redirect.
It should be `https://127.0.0.1/loginGoogle/callbackGoogle`

**Comment by shashi278** [comment]
And thanks for pointing this out. It should be there in the docs

**Comment by YuriSilenok** [comment]
@shashi278 
This is a victory!
Thank you very much.
![image](https://user-images.githubusercontent.com/14871471/154816851-f595c432-c8b0-41b4-b960-6d8455e87c64.png)
