### ISSUE TITLE
Builodzer Problem, and testing probelm

### ISSUE THREAD

**Issue by Matan22g** [shashi278/social-auth-kivy#2]
Hey, first of all thank you for your work, this facebook/google auth will be a gread asset to kivy, 

I'm trying to integrate this lib with my project, but haven't found a way to test it first on windows, cause it uses libs like android that only on a smartphone can be used, do you know a way to test this lib on windows with pycharm?

So I've tried to compile it with buildozer without testing it, just adding a google auth, but if failed, So I've decided to build your demo first, with your specs, and it failed too. So is it a problem with my buildozer? (It builds my app perfectly and other demo apps)
or with your code/lib?
the error is here: https://pastebin.pl/view/1dd6d895

**Comment by shashi278** [comment]
You cannot test it on any platform except android 'cause, as you already mentioned, it has dependencies that only android can provide. So you'll have to build an apk and test that.

And about the error you're getting, it seems some kind of environment error to me. Make sure you can create a simple hello world app inside the same env and test it on android before going for kivyauth.

**Comment by Matan22g** [comment]
Ok thats what I thought, just had to ask you if there's a way to debug it first..
As for a simple app to work - an hello world working perfectly fine in the same environment, and even a much more complicated app that Im working on with 7000+ lines of code is working just fine. 
Ive used the demo folder cloned from your git and with the same specs you got there, and it didnt work..
Maybe it works only with certain buildozer release? Or other things that might have changed.. can you still compile it to an apk?
Whats env are you running it on?

**Comment by shashi278** [comment]
I'm using the default buildozer version. It's 1.0 in my case.
And yes I just tried and I can still compile it into an apk. There's nothing special about env in my case. In fact, I'm not using any virtualenv for this. The error you're getting seems to be related to your env. Did you try asking about it in the kivy discord channel?
