### ISSUE TITLE
RectangularElevationBehavior - Deprecated since version 1.1.0.

### ISSUE THREAD

**Issue by psiu7217** [shashi278/social-auth-kivy#22]
You need to update the repository.
The current version of kiwi is 1.1.1

class kivymd.uix.behaviors.elevation.RectangularElevationBehavior(**kwargs)
Deprecated since version 1.1.0.

Use [CommonElevationBehavior](https://kivymd.readthedocs.io/en/1.1.1/behaviors/elevation/#kivymd.uix.behaviors.elevation.CommonElevationBehavior) class instead.

**Comment by shashi278** [comment]
@psiu7217 Yeah I tried it recently after many days and realised the same.

**Comment by shashi278** [comment]
Updated it now.
