### ISSUE TITLE
Google Login Access Denied On Ubuntu & "Login Error" On Android

### ISSUE THREAD

**Issue by boyintheroom** [shashi278/social-auth-kivy#25]
**Describe the bug**
i've done exactly as the repo says and im getting this error on logging in on pc and on mobile i get the pop box of accounts of google and when i press on the accounts i gives a toast message"login error"

**To Reproduce**
1. press login button of 'main' code with your own google id and secret on OS ubuntu 20.04

**Screenshots**
![IMG-20221105-WA0001](https://user-images.githubusercontent.com/97958343/200884794-6564d0d9-6dda-45b0-814a-025a5f701382.jpeg)

![20221109_220311](https://user-images.githubusercontent.com/97958343/200887062-d9251d8b-2c57-4821-bd0e-78da5dacfa80.jpg)

screen shot is taken after the google button takes to google logon and it shows access denied invalid request and press to see the error details. so its the error.

**Desktop (please complete the following information):**
 - OS: Ubuntu

**Smartphone (please complete the following information):**
 - Device: Samsung J7 Max
 - OS: Android 8.1

**Comment by shashi278** [comment]
@boyintheroom Did you manage to get away from this?

**Comment by shashi278** [comment]
@boyintheroom I'm closing this. Feel free to open again if you still face this issue.
