### ISSUE TITLE
Error while logging with Google

### ISSUE THREAD

**Issue by kapi0okapi** [shashi278/social-auth-kivy#26]
Hi.
I tried to implement a function that gives you the ability to log in to the application using google. I did everything according to the instructions, however, when I try to log in, after selecting an account, it says "Internal Server Error". The program shows the following error:
![image](https://user-images.githubusercontent.com/120471263/207323277-7b24bc4a-cbb8-4266-a06b-7ad145a93fca.png)

**Comment by shashi278** [comment]
Hey, @kapi0okapi thanks for pointing out. I think #21 also points the same. Maybe this weekend or before that.

**Comment by shashi278** [comment]
Although duplicate but still a valid issue so I've opened it again.

**Comment by ravcom71** [comment]
I have the same problem. Is solution of this anywhere?

**Comment by shashi278** [comment]
@ravcom71 @kapi0okapi It's been fixed in latest version 2.3.3. I'm closing this issue but feel free to open a new one.

**Comment by ravcom71** [comment]
Thanks!
