### ISSUE TITLE
Auto-Login Feature

### ISSUE THREAD

**Issue by Kulothungan16** [shashi278/social-auth-kivy#6]
please provide auto-login functionality in google auth and other services

**Comment by shashi278** [comment]
@Kulothungan16 that's a good feature! Also, I had it in my mind some times ago but, I don't remember, there were some complications regarding this at that time :thinking: . I'll see into it again.

**Comment by Kulothungan16** [comment]
thx bro. If I login and close the app without logging out and when reopening the app, it crashes I think it's because of it had been already a logined.

**Comment by shashi278** [comment]
It doesn't crash upon re-opening for me. However there is a known issue of crashing if you logged in using facebook and then closed the app without logging out and again when you open the app and try logging in using facebook.
