### ISSUE TITLE
Buildozer build fails with Gradle deprecation warnings

### ISSUE THREAD

**Issue by animalmutch** [shashi278/social-auth-kivy#8]
**Describe the bug**
Buildozer build fails. It looks like this is because KivyAuth uses deprecated and obsolete Gradle features.

**To Reproduce**
Using latest Buildozer docker image, prerequisites as per the KivyAuth docs

**Desktop (please complete the following information):**
 - OS: Windows 10, but actually a docker image running on Ubuntu with WSL2 backend (yes, I've successfully built APKs using this setup in the past. It's specifically adding the 'com.google.android.gms:play-services-auth:18.0.0' Gradle dependency that makes the build fail.)

**Additional context**
Logs are as follows:

[INFO]:    Detected highest available build tools version to be 30.0.3
[DEBUG]:   -> running gradlew assembleDebug
[DEBUG]:        Starting a Gradle Daemon, 1 incompatible and 1 stopped Daemons could not be reused, use --status for details
[DEBUG]:
[DEBUG]:        > Configure project :
[DEBUG]:        WARNING: Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.
[DEBUG]:        It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html
[DEBUG]:        /home/user/.gradle/caches/transforms-2/files-2.1/e828b7fe62022acba170576d3a0a6a8a/res/values/values.xml:133:5-70: AAPT: error: resource android:attr/fontVariationSettings not found.
[DEBUG]:
[DEBUG]:        /home/user/.gradle/caches/transforms-2/files-2.1/e828b7fe62022acba170576d3a0a6a8a/res/values/values.xml:133:5-70: AAPT: error: resource android:attr/ttcIndex not found.
[DEBUG]:
[DEBUG]:        error: failed linking references.
[DEBUG]:        > IDLE
[DEBUG]:        > Task :processDebugResources FAILED
[DEBUG]:
[DEBUG]:        FAILURE: Build failed with an exception.
[DEBUG]:
[DEBUG]:        * What went wrong:
[DEBUG]:        Execution failed for task ':processDebugResources'.
[DEBUG]:        > Failed to process resources, see aapt output above for details.
[DEBUG]:
[DEBUG]:        * Try:
[DEBUG]:        Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
[DEBUG]:
[DEBUG]:        * Get more help at https://help.gradle.org
[DEBUG]:
[DEBUG]:        Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
[DEBUG]:        Use '--warning-mode all' to show the individual deprecation warnings.
[DEBUG]:        See https://docs.gradle.org/6.4.1/userguide/command_line_interface.html#sec:command_line_warnings
[DEBUG]:
[DEBUG]:        BUILD FAILED in 45s
[DEBUG]:        13 actionable tasks: 13 executed

Exception in thread background thread for pid 3053:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/user/.local/lib/python3.8/site-packages/sh.py", line 1637, in wrap
    fn(*rgs, **kwargs)
  File "/home/user/.local/lib/python3.8/site-packages/sh.py", line 2561, in background_thread
    handle_exit_code(exit_code)
  File "/home/user/.local/lib/python3.8/site-packages/sh.py", line 2265, in fn
    return self.command.handle_command_exit_code(exit_code)
  File "/home/user/.local/lib/python3.8/site-packages/sh.py", line 865, in handle_command_exit_code
    raise exc
sh.ErrorReturnCode_1:

  RAN: /home/user/hostcwd/.buildozer/android/platform/build-armeabi-v7a/dists/ccc__armeabi-v7a/gradlew assembleDebug

  STDOUT:
Starting a Gradle Daemon, 1 incompatible and 1 stopped Daemons could not be reused, use --status for details

> Configure project :
WARNING: Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.
It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html
/home/user/.gradle/caches/transforms-2/files-2.1/e828b7fe62022acba170576d3a0a6a8a/res/values/values.xml:133:5-70: AAPT: error: resource android:attr/fontVariationSettings not found.

/home/user/.gradle/caches/transforms-2/files-2.1/e828b7fe62022acba170576d3a0a6a8a/res/values/values.xml:133:5-70: AAPT: error: resource android:attr/ttcIndex not found.

error: failed linking references.
> IDLE
> Task :processDebugResources FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':processDebugResources'.
> Failed to process resources, see aapt output above for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.4.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 45s
13 actionable tasks: 13 executed

  STDERR:

[INFO]:    STDOUT (last 20 lines of 61):
        Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.4.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 45s
13 actionable tasks: 13 executed

[INFO]:    STDERR:

[INFO]:    COMMAND:
cd /home/user/hostcwd/.buildozer/android/platform/build-armeabi-v7a/dists/ccc__armeabi-v7a && /home/user/hostcwd/.buildozer/android/platform/build-armeabi-v7a/dists/ccc__armeabi-v7a/gradlew assembleDebug

[WARNING]: ERROR: /home/user/hostcwd/.buildozer/android/platform/build-armeabi-v7a/dists/ccc__armeabi-v7a/gradlew failed!
WARNING: Received a --sdk argument, but this argument is deprecated and does nothing.
No setup.py/pyproject.toml used, copying full private data into .apk.
Applying Java source code patches...
Applying patch: src/patches/SDLActivity.java.patch
# Command failed: /usr/bin/python3 -m pythonforandroid.toolchain apk --debug --bootstrap=sdl2 --dist_name ccc --name CCC --version 0.1 --package org.example.ccc.ccc --minsdk 21 --ndk-api 21 --private /home/user/hostcwd/.buildozer/android/app --permission INTERNET --android-entrypoint org.kivy.android.PythonActivity --android-apptheme @android:style/Theme.NoTitleBar --presplash /home/user/hostcwd/ccc/ccc/res/splash.png --icon /home/user/hostcwd/ccc/ccc/res/icon.png --orientation sensor --window --copy-libs --depend com.google.android.gms:play-services-auth:18.0.0 --arch armeabi-v7a --color=always --storage-dir="/home/user/hostcwd/.buildozer/android/platform/build-armeabi-v7a" --ndk-api=21 --ignore-setup-py
# ENVIRONMENT:
#     PATH = '/home/user/.buildozer/android/platform/apache-ant-1.9.4/bin:/home/user/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
#     HOSTNAME = '11ca977794dc'
#     TERM = 'xterm'
#     USER = 'user'
#     HOME_DIR = '/home/user'
#     WORK_DIR = '/home/user/hostcwd'
#     SRC_DIR = '/home/user/src'
#     LANG = 'en_US.UTF-8'
#     LANGUAGE = 'en_US.UTF-8'
#     LC_ALL = 'en_US.UTF-8'
#     HOME = '/home/user'
#     PACKAGES_PATH = '/home/user/.buildozer/android/packages'
#     ANDROIDSDK = '/home/user/.buildozer/android/platform/android-sdk'
#     ANDROIDNDK = '/home/user/.buildozer/android/platform/android-ndk-r19c'
#     ANDROIDAPI = '27'
#     ANDROIDMINAPI = '21'
#
# Buildozer failed to execute the last command
# The error might be hidden in the log above this error
# Please read the full log, and search for it before
# raising an issue with buildozer itself.
# In case of a bug report, please add a full log with log_level = 2

**Comment by shashi278** [comment]
Thanks for the detailed log. It seems to be a known issue with `androidapi` less than 28. As I can see in the log, you're trying to build it for `androidapi=27` but `fontVariationSettings` and `ttcIndex` are added in api level 28. 
Update api level in your buildozer.spec file:
`android.api = 28` (or above)

Clean: `buildozer android clean`
Then rebuild.

**Comment by animalmutch** [comment]
Thanks for getting back to me so quickly. I've rebuilt with API 28, and the build now works. However, the app fails at runtime with the following ADB logcat output:

`01-03 22:09:29.090 31414 31435 I python  :    File "/home/user/hostcwd/.buildozer/android/app/main.py", line 7, in <module>
01-03 22:09:29.090 31414 31435 I python  :    File "/home/user/hostcwd/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/ccc/kivyauth/google_auth.py", line 6, in <module>
01-03 22:09:29.091 31414 31435 I python  :    File "/home/user/hostcwd/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/ccc/jnius/reflect.py", line 208, in autoclass
01-03 22:09:29.092 31414 31435 I python  :    File "jnius/jnius_export_func.pxi", line 28, in jnius.jnius.find_javaclass01-03 22:09:29.092 31414 31435 I python  :  jnius.jnius.JavaException: Class not found b'com/google/android/gms/auth/api/signin/GoogleSignInOptions'`

**Comment by animalmutch** [comment]
PS - Device is a Motorola G6 Play, running Android 9 (fully updated)

**Comment by shashi278** [comment]
> Class not found b'com/google/android/gms/auth/api/signin/GoogleSignInOptions

It's apparently because you forgot to add `com.google.android.gms:play-services-auth:18.0.0` as a gradle_dependencies inside your buildozer specification file. I suggest you have a look at [buildozer.spec](https://github.com/shashi278/social-auth-kivy/blob/master/demo/buildozer.spec#L159) file inside the demo application.

**Comment by animalmutch** [comment]
D'oh! That was from trying things out to try to debug the original problem! Thanks. Will have another go.

**Comment by animalmutch** [comment]
After a complete rebuild of my Buildozer docker image to get the correct API level installed, I can confirm it's now working. Great stuff. Thanks for your help!

**Comment by shashi278** [comment]
Thanks for confirming!
